import type { LucideIcon } from 'lucide-react';
import {
  Music,
  Dumbbell,
  Gamepad2,
  ChefHat,
  Brain,
  ShoppingBag,
  Theater,
  SkipForward,
  Palette,
  Film,
  BookOpen,
  Mountain,
  Wind,
  UtensilsCrossed,
  Lightbulb,
  Globe,
  Heart,
  Users,
  Sparkles,
  Wine,
  Leaf,
} from 'lucide-react';

// Icône associée à chaque sous-catégorie d'événement
export const SUBCATEGORY_ICONS: Record<string, LucideIcon> = {
  // Arts & Culture
  CONCERT: Music,
  THEATRE: Theater,
  SPECTACLE: SkipForward,
  DANSE: Music,
  CINEMA: Film,
  ART: Palette,
  PEINTURE: Palette,
  PHOTOGRAPHIE: Film,
  EXPOSITION: Sparkles,
  MUSEE: BookOpen,
  LECTURE: BookOpen,
  // Sports & Bien-être
  TRAIL: Mountain,
  SPORT: Dumbbell,
  COMPETITION: Dumbbell,
  RANDONNEE: Mountain,
  NAUTISME: Wind,
  YOGA: Heart,
  MEDITATION: Heart,
  BIENETRE: Heart,
  DEVELOPPEMENTPERSONNEL: Brain,
  // Loisirs & Divertissements
  JEUX: Gamepad2,
  JEUXVIDEO: Gamepad2,
  ESPORT: Gamepad2,
  MANGA: BookOpen,
  COSPLAY: Sparkles,
  FESTIVAL: Sparkles,
  FETELOCALE: Users,
  FERIA: Users,
  SOIREE: Users,
  JOURNEE: Sparkles,
  // Gastronomie
  REPAS: UtensilsCrossed,
  DEJEUNER: UtensilsCrossed,
  COURSDECUISINE: ChefHat,
  DEGUSTATION: Wine,
  BAR: Wine,
  // Savoir & Découverte
  CONFERENCE: Brain,
  FORMATION: BookOpen,
  LANGUES: Globe,
  SCIENCE: Lightbulb,
  DECOUVERTE: Sparkles,
  PATRIMOINE: Globe,
  VISITE: Globe,
  ATELIER: Lightbulb,
  // Marché & Commerce
  MARCHE: ShoppingBag,
  BROCANTE: ShoppingBag,
  VIDEGRENIER: ShoppingBag,
  ENCHERES: ShoppingBag,
  // Causes Sociales & Écologie
  ANIMAUX: Heart,
  BENEVOLAT: Users,
  ECOLOGIE: Leaf,
  SOLIDARITE: Heart,
};
