export enum EventCategory {
  CONCERT = 'CONCERT',
  CINEMA = 'CINEMA',
  THEATRE = 'THEATRE',
  SPECTACLE = 'SPECTACLE',
  FANFARE = 'FANFARE',
  DANSE = 'DANSE',
  COURSDEDANSE = 'COURSDEDANSE',
  ART = 'ART',
  PEINTURE = 'PEINTURE',
  PHOTOGRAPHIE = 'PHOTOGRAPHIE',
  EXPOSITION = 'EXPOSITION',
  MUSEE = 'MUSEE',
  LANCEMENTDELIVRE = 'LANCEMENTDELIVRE',
  ENFANTS = 'ENFANTS',
  JEUX = 'JEUX',
  JEUXVIDEO = 'JEUXVIDEO',
  SOIREEJEUX = 'SOIREEJEUX',
  LECTURE = 'LECTURE',
  REPAS = 'REPAS',
  DEJEUNER = 'DEJEUNER',
  COURSDECUISINE = 'COURSDECUISINE',
  DEGUSTATION = 'DEGUSTATION',
  SOIREE = 'SOIREE',
  BAR = 'BAR',
  FESTIVAL = 'FESTIVAL',
  FETELOCALE = 'FETELOCALE',
  FERIA = 'FERIA',
  NATURE = 'NATURE',
  RANDONNEE = 'RANDONNEE',
  TRAIL = 'TRAIL',
  OUTDOOR = 'OUTDOOR',
  MARCHE = 'MARCHE',
  NEIGE = 'NEIGE',
  NAUTISME = 'NAUTISME',
  AVENTURE = 'AVENTURE',
  YOGA = 'YOGA',
  MEDITATION = 'MEDITATION',
  BIENETRE = 'BIENETRE',
  DEVELOPPEMENTPERSONNEL = 'DEVELOPPEMENTPERSONNEL',
  CONFERENCE = 'CONFERENCE',
  FORMATION = 'FORMATION',
  LANGUES = 'LANGUES',
  SALONPROFESSIONNEL = 'SALONPROFESSIONNEL',
  SCIENCE = 'SCIENCE',
  DECOUVERTE = 'DECOUVERTE',
  PATRIMOINE = 'PATRIMOINE',
  VISITE = 'VISITE',
  ATELIER = 'ATELIER',
  BRICOLAGE = 'BRICOLAGE',
  MODE = 'MODE',
  ANIMAUX = 'ANIMAUX',
  JARDINAGE = 'JARDINAGE',
  FERME = 'FERME',
  BENEVOLAT = 'BENEVOLAT',
  ECOLOGIE = 'ECOLOGIE',
  SOLIDARITE = 'SOLIDARITE',
  RENCONTRE = 'RENCONTRE',
  EVENEMENTCARITATIF = 'EVENEMENTCARITATIF',
  ESPORT = 'ESPORT',
  TECHNOLOGIE = 'TECHNOLOGIE',
  MANGA = 'MANGA',
  COSPLAY = 'COSPLAY',
  TOURNOIJEUXVIDEO = 'TOURNOIJEUXVIDEO',
  BROCANTE = 'BROCANTE',
  VIDEGRENIER = 'VIDEGRENIER',
  ENCHERES = 'ENCHERES',
  SPORT = 'SPORT',
  COMPETITION = 'COMPETITION',
  RENCONTRESPORTIVE = 'RENCONTRESPORTIVE',
  JOURNEE = 'JOURNEE',
}

// Labels en français pour l'affichage dans le frontend
export const EventCategoryLabels: Record<EventCategory, string> = {
  [EventCategory.CONCERT]: 'Concert',
  [EventCategory.CINEMA]: 'Cinéma',
  [EventCategory.THEATRE]: 'Théâtre',
  [EventCategory.SPECTACLE]: 'Spectacle',
  [EventCategory.FANFARE]: 'Fanfare',
  [EventCategory.DANSE]: 'Danse',
  [EventCategory.COURSDEDANSE]: 'Cours de danse',
  [EventCategory.ART]: 'Art',
  [EventCategory.PEINTURE]: 'Peinture',
  [EventCategory.PHOTOGRAPHIE]: 'Photographie',
  [EventCategory.EXPOSITION]: 'Exposition',
  [EventCategory.MUSEE]: 'Musée',
  [EventCategory.LANCEMENTDELIVRE]: 'Lancement de livre',
  [EventCategory.ENFANTS]: 'Enfants',
  [EventCategory.JEUX]: 'Jeux',
  [EventCategory.JEUXVIDEO]: 'Jeux vidéo',
  [EventCategory.SOIREEJEUX]: 'Soirée jeux',
  [EventCategory.LECTURE]: 'Lecture',
  [EventCategory.REPAS]: 'Repas',
  [EventCategory.DEJEUNER]: 'Déjeuner',
  [EventCategory.COURSDECUISINE]: 'Cours de cuisine',
  [EventCategory.DEGUSTATION]: 'Dégustation',
  [EventCategory.SOIREE]: 'Soirée',
  [EventCategory.BAR]: 'Bar',
  [EventCategory.FESTIVAL]: 'Festival',
  [EventCategory.FETELOCALE]: 'Fête locale',
  [EventCategory.FERIA]: 'Féria',
  [EventCategory.NATURE]: 'Nature',
  [EventCategory.RANDONNEE]: 'Randonnée',
  [EventCategory.TRAIL]: 'Trail',
  [EventCategory.OUTDOOR]: 'Outdoor',
  [EventCategory.MARCHE]: 'Marche',
  [EventCategory.NEIGE]: 'Neige',
  [EventCategory.NAUTISME]: 'Nautisme',
  [EventCategory.AVENTURE]: 'Aventure',
  [EventCategory.YOGA]: 'Yoga',
  [EventCategory.MEDITATION]: 'Méditation',
  [EventCategory.BIENETRE]: 'Bien-être',
  [EventCategory.DEVELOPPEMENTPERSONNEL]: 'Développement personnel',
  [EventCategory.CONFERENCE]: 'Conférence',
  [EventCategory.FORMATION]: 'Formation',
  [EventCategory.LANGUES]: 'Langues',
  [EventCategory.SALONPROFESSIONNEL]: 'Salon professionnel',
  [EventCategory.SCIENCE]: 'Science',
  [EventCategory.DECOUVERTE]: 'Découverte',
  [EventCategory.PATRIMOINE]: 'Patrimoine',
  [EventCategory.VISITE]: 'Visite',
  [EventCategory.ATELIER]: 'Atelier',
  [EventCategory.BRICOLAGE]: 'Bricolage',
  [EventCategory.MODE]: 'Mode',
  [EventCategory.ANIMAUX]: 'Animaux',
  [EventCategory.JARDINAGE]: 'Jardinage',
  [EventCategory.FERME]: 'Ferme',
  [EventCategory.BENEVOLAT]: 'Bénévolat',
  [EventCategory.ECOLOGIE]: 'Écologie',
  [EventCategory.SOLIDARITE]: 'Solidarité',
  [EventCategory.RENCONTRE]: 'Rencontre',
  [EventCategory.EVENEMENTCARITATIF]: 'Événement caritatif',
  [EventCategory.ESPORT]: 'E-sport',
  [EventCategory.TECHNOLOGIE]: 'Technologie',
  [EventCategory.MANGA]: 'Manga',
  [EventCategory.COSPLAY]: 'Cosplay',
  [EventCategory.TOURNOIJEUXVIDEO]: 'Tournoi jeux vidéo',
  [EventCategory.BROCANTE]: 'Brocante',
  [EventCategory.VIDEGRENIER]: 'Vide-grenier',
  [EventCategory.ENCHERES]: 'Enchères',
  [EventCategory.SPORT]: 'Sport',
  [EventCategory.COMPETITION]: 'Compétition',
  [EventCategory.RENCONTRESPORTIVE]: 'Rencontre sportive',
  [EventCategory.JOURNEE]: 'Journée',
};
